Так надо
skrylnikov/Vsratometr-tg-bot pull request #7
Opened 2021-06-30 06:17 UTC by kotovs

Сыр

2021-06-30 12:57 UTC, skrylnikov requested changes

2021-06-30 12:57 UTC, skrylnikov commented on src/service/token-list.ts
> +  { token: 'не за что'},
говно! работать не будет!

2021-07-08 18:47 UTC, kotovs reviewed
Чот сделал

2021-07-08 18:50 UTC, kotovs commented
Конфликт решен

2021-07-14 17:56 UTC, merged